#
# CircleCI Integration Tests.
# Run locally with circleci local:
#
#   `circleci build`
#
# For using anchors in circle.yml see https://circleci.com/docs/2.0/writing-yaml/#anchors-and-aliases
#
# NOTE: As of today 2018-11 circleci local doesn't
#       support caching.
#
anchors:
- key_cache: &key_cache v1-cache-{{ checksum "pom.xml" }}

version: 2
jobs:
  test: &base
    working_directory: ~/caldav4j
    # Build in the primary docker container
    #  and connecting to the baikal server provided
    #  by the second container.
    docker:
      - image: circleci/openjdk:8-jdk-browsers
      - image: ioggstream/baikal:with-testuser
    steps:
    - checkout

    # restore the saved cache after the first run or if `pom.xml` has changed
    # REMEMBER: cache doesn't affect local builds
    - restore_cache:
        key: *key_cache

    - run: mvn dependency:go-offline # gets the project dependencies

    - save_cache: # saves the project dependencies
        paths:
          - ~/.m2
        key: *key_cache

    - run: mvn package -B -V -Dcaldav4jUri="http://testuser:testuser@localhost/cal.php/calendars/testuser/"

    - persist_to_workspace:
        root: .
        paths:
          - .

  deploy:
    <<: *base
    steps:
    - checkout

    # restore the saved cache after the first run or if `pom.xml` has changed
    # REMEMBER: cache doesn't affect local builds
    - restore_cache:
        key: *key_cache

    - run: mvn dependency:go-offline # gets the project dependencies

    - save_cache: # saves the project dependencies
        paths:
        - ~/.m2
        key: *key_cache

    - run: mvn deploy -B -V -Dcaldav4jUri="http://testuser:testuser@localhost/cal.php/calendars/testuser/"  -s .circleci/settings.xml

  sign-no-test:
    <<: *base
    steps:
    # Reuse the workspace from the build job
    - attach_workspace:
        at: .

    - run:
        name: import GPG key
        command: echo -e "$GPG_KEY" | gpg --import --no-tty --batch --yes

    - run: gpg --list-keys

    # Tests are run before signing.
    - run: mvn package gpg:sign -s .circleci/settings.xml -Dmaven.test.skip -Pcentral

workflows:
  version: 2
  continuous-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
  sign:
    jobs:
      - test
      - sign-no-test:
          requires:
            - test
          filters:
            branches:
              only:
                - /test.*/
  do-test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
                - /test.*/

